### ISSUE TITLE
String table get in conflict with the String Java class

### ISSUE THREAD

**Issue by loucass003** [SlimeVR/SolarXR-Protocol#47]
The library does not compile because the string table declared in data types gets in conflict with the java String class

_Originally posted by @loucass003 in https://github.com/SlimeVR/SolarXR-Protocol/pull/44#discussion_r1014752946_

**Comment by TheButlah** [comment]
LMAO

**Comment by TheDevMinerTV** [comment]
🚀

**Comment by loucass003** [comment]
Java moment
Big oof
